//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TareaCarlosMarcoJosue2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdventureWorks2016Entities1 : DbContext
    {
        public AdventureWorks2016Entities1()
            : base("name=AdventureWorks2016Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<VistaPersonas> VistaPersonas { get; set; }
        public virtual DbSet<VistaRecursosHumanos> VistaRecursosHumanos { get; set; }
        public virtual DbSet<VistaProducto> VistaProducto { get; set; }
    }
}
