//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TareaCarlosMarcoJosue2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaRecursosHumano
    {
        public string PrimerNombre { get; set; }
        public string SegundoNombre { get; set; }
        public string Apellidos { get; set; }
        public string Titulo { get; set; }
        public string Genero { get; set; }
        public System.DateTime FechaContratacion { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string TipoSalario { get; set; }
        public decimal TasaSalario { get; set; }
        public string FrecuenciaSalario { get; set; }
        public string Estado { get; set; }
        public short HorasIndemnizadas { get; set; }
        public short HorasVacaiones { get; set; }
        public short IDDepartamento { get; set; }
        public string Departmento { get; set; }
        public string GrupoDepartamento { get; set; }
        public byte IDTurno { get; set; }
        public string Turno { get; set; }
    }
}
