//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TareaCarlosMarcoJosue2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaPersona
    {
        public string Titulo { get; set; }
        public string NombreCompleto { get; set; }
        public string Correo { get; set; }
        public string PhoneNumber { get; set; }
        public string City { get; set; }
        public string AddressLine1 { get; set; }
        public string Name { get; set; }
    }
}
