//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TareaCarlosMarcoJosue2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaProducto
    {
        public int ProductID { get; set; }
        public string Producto { get; set; }
        public string NumeroDeProducto { get; set; }
        public string Color { get; set; }
        public string SubCategoria { get; set; }
        public string Categoria { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string Description { get; set; }
    }
}
