//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TareaCarlosMarcoJosue2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaRecursosHumanos
    {
        public string PrimerNombre { get; set; }
        public string SegundoNombre { get; set; }
        public string Apellidos { get; set; }
        public string Titulo { get; set; }
        public string Genero { get; set; }
        public System.DateTime FechaContratacion { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string TipoSalario { get; set; }
        public decimal TasaSalario { get; set; }
        public string FrecuenciaSalario { get; set; }
        public string Estado { get; set; }
        public short HorasIndemnizadas { get; set; }
        public short HorasVacaiones { get; set; }
        public short IDDepartamento { get; set; }
        public string Departmento { get; set; }
        public string GrupoDepartamento { get; set; }
        public byte IDTurno { get; set; }
        public string Turno { get; set; }
    }
}
