//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TareaCarlosMarcoJosue2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaPersonas
    {
        public string Titulo { get; set; }
        public string NombreCompleto { get; set; }
        public string Correo { get; set; }
        public string PhoneNumber { get; set; }
        public string City { get; set; }
        public string AddressLine1 { get; set; }
        public string Name { get; set; }
    }
}
